#!/usr/bin/env python

def build(bld):
	prog = bld(features='c cprogram')
	# symbolic name used to reference this object
	prog.name = 'sudoku.myapp'
	# name of the resulting program
	prog.target = 'sudoku'
	prog.source = ['Sudoku.vala', 'SudokuGenerator.vala', 'SudokuGrid.vala',
	     'SudokuWidget.vala']
	# libraries to link against
	prog.uselib = 'GTK+ GOBJECT GLIB'
	# Vala packages to use
	prog.packages = 'gtk+-3.0'
